from marshmallow import Schema, fields, validate, ValidationError

class GenCharSchema(Schema):
    discord_id = fields.String(required=True, validate=validate.Length(equal=18))
    race = fields.Bool(required=True)

class AddUserSchema(Schema):
    discord_id  = fields.String(required=True)
    discord_name = fields.String(required=True)

class RandomCharacterSchema(Schema):
    discord_id = fields.String(required=True)

class AddWhitehackCharacterSchema(Schema):
    user_id = fields.Integer(required=True, validate=validate.Equal('DEFAULT'))
    char_id = fields.Integer(required= True)
    name = fields.String(required=True)
    archetype = fields.String()
    group1 = fields.String()
    group2 = fields.String()
    group3 = fields.String()
    group4 = fields.String()
    group5 = fields.String()
    stat_str = fields.Integer()
    stat_dex = fields.Integer()
    stat_con = fields.Integer()
    stat_int = fields.Integer()
    stat_wis = fields.Integer()
    str_group = fields.String()
    dex_group = fields.String()
    con_group = fields.String()
    int_group = fields.String()
    wis_group = fields.String()
    ST = fields.Integer()
    HP = fields.Integer()
    AC = fields.Integer()
    MV = fields.Integer()
    AV = fields.Integer()

class UpdateWhitehackCharacterSchema(Schema):
    user_id = fields.Integer(missing=None)
    char_id = fields.Integer(required= True)
    name = fields.String(required=True)
    archetype = fields.String(missing=None)
    group1 = fields.String(missing=None)
    group2 = fields.String(missing=None)
    group3 = fields.String(missing=None)
    group4 = fields.String(missing=None)
    group5 = fields.String(missing=None)
    stat_str = fields.Integer(missing=None)
    stat_dex = fields.Integer(missing=None)
    stat_con = fields.Integer(missing=None)
    stat_int = fields.Integer(missing=None)
    stat_wis = fields.Integer(missing=None)
    str_group = fields.String(missing=None)
    dex_group = fields.String(missing=None)
    con_group = fields.String(missing=None)
    int_group = fields.String(missing=None)
    wis_group = fields.String(missing=None)
    ST = fields.Integer(missing=None)
    HP = fields.Integer(missing=None)
    AC = fields.Integer(missing=None)
    MV = fields.Integer(missing=None)
    AV = fields.Integer(missing=None)