from marshmallow import Schema, fields, validate, ValidationError

class AddWhitehackCharacterSchema(Schema):
    user_id = fields.String(required=True, validate=validate.Equal('DEFAULT'))
    char_id = fields.Integer(required= True)
    name = fields.String(required=True)
    archetype = fields.String()
    group1 = fields.String()
    group2 = fields.String()
    group3 = fields.String()
    group4 = fields.String()
    group5 = fields.String()
    stat_str = fields.Integer()
    stat_dex = fields.Integer()
    stat_con = fields.Integer()
    stat_int = fields.Integer()
    stat_wis = fields.Integer()
    str_group = fields.String()
    dex_group = fields.String()
    con_group = fields.String()
    int_group = fields.String()
    wis_group = fields.String()
    ST = fields.Integer()
    HP = fields.Integer()
    AC = fields.Integer()
    MV = fields.Integer()
    AV = fields.Integer()